### ISSUE TITLE
Publish to Rubygem

### ISSUE THREAD

**Issue by mufid** [eliotsykes/rails-static-router#2]
Hi Eliot. Thank you very much for this library. I even use this in production. However, i have multiple apps, and it would be very handy if i can put this library as simple as `gem install rails-static-router`

I can do a PR for this, but needs your consent to publish it under your name.

**Comment by eliotsykes** [comment]
Hi @mufid, I'm so pleased to read this today 😀 thank you!

I think the gem would be best stewarded by a developer who's using it regularly like yourself (I've not used the static router for a while). What do you think about publishing it under your own account?

**Comment by mufid** [comment]
Sure. I will make a fork of this repo.

Thanks!

**Comment by eliotsykes** [comment]
Fantastic 😄 !

**Comment by mufid** [comment]
You're welcome Eliot :D 

I've published it here: https://rubygems.org/gems/rails-static-router
